language: node_js

node_js:
  - "7"

before_script:
  - "gulp dist"

# https://blog.travis-ci.com/2013-12-05-speed-up-your-builds-cache-your-dependencies
cache:
  yarn: true
  directories:
    - "bower_components"
    - "node_modules"

notifications:
  email: false
